import type { Metadata } from "next";
import "./globals.css";

import { Vazirmatn } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"], 
  weight: ["400", "500", "700"], 
  display: "swap",
});



export const metadata: Metadata = {
  title: "غذای خونگی مامان پز",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={vazirmatn.className}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
